name: Generate JSON Schema

on:
  push:
    branches: ['master']
    paths:
      - 'traiNNer/utils/redux_options.py'  # Only trigger if this file is changed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_schema:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Generate the JSON schema
      - name: Generate JSON Schema
        run: |
          python scripts/options/generate_schema.py

      # Commit changes to a new branch
      - name: Commit changes to new branch
        run: |
          git checkout -b update-json-schema
          git add schemas/redux-config.schema.json
          git commit -m "Update generated JSON schema"

      # Push the new branch to GitHub
      - name: Push new branch
        run: |
          git push origin update-json-schema

      # Create a pull request targeting master
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update generated JSON schema"
          body: "This PR updates the generated JSON schema."
          head: update-json-schema
          base: master
          author: 'GitHub Actions <actions@github.com>'
